scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile1`, function (sprite, location) {
    game.gameOver(true)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile3`, function (sprite, location) {
    myEnemy = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ffaaaaff........
        .......faaaaaaaaf.......
        .......faa2222aaf.......
        ......faaa2ff2aaaf......
        ......faaa2222aaaf......
        ......faaaaaaaaaaf......
        ......faa2faaf2aaf......
        ......faa2faaf2aaf......
        .......faaaaaaaaf.......
        .....ffffaaaaaaffff.....
        ....ffaaaaafafaaaaff....
        ....faaaaaffffaaaaaf....
        ....fafaffffffafafaf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    myEnemy.follow(mySprite)
    tiles.placeOnRandomTile(myEnemy, sprites.dungeon.floorLightMoss)
})
info.onCountdownEnd(function () {
    game.gameOver(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    game.gameOver(false)
})
let myEnemy: Sprite = null
let mySprite: Sprite = null
info.startCountdown(30)
mySprite = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........3...............
    ........................
    ......555...............
    5f5f5f5f5...............
    5f5f5f555...............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
myEnemy = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ffaaaaff........
    .......faaaaaaaaf.......
    .......faa2222aaf.......
    ......faaa2ff2aaaf......
    ......faaa2222aaaf......
    ......faaaaaaaaaaf......
    ......faa2faaf2aaf......
    ......faa2faaf2aaf......
    .......faaaaaaaaf.......
    .....ffffaaaaaaffff.....
    ....ffaaaaafafaaaaff....
    ....faaaaaffffaaaaaf....
    ....fafaffffffafafaf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
myEnemy.follow(mySprite)
tiles.setCurrentTilemap(tilemap`niveau1`)
tiles.placeOnRandomTile(mySprite, sprites.dungeon.collectibleInsignia)
tiles.placeOnRandomTile(myEnemy, assets.tile`myTile3`)
scene.cameraFollowSprite(mySprite)
game.showLongText("DONT GO TO GRAVES", DialogLayout.Bottom)
